version: '3'

services:
#  cache:
#    image: redis:7.0.4-alpine
#    restart: always
#    ports:
#      - '6379:6379'
#    command: redis-server
#    volumes:
#      - cache:/data
#
#volumes:
#    cache:
#      driver: local
  redis:
    image: redis:7.0.4-alpine
    container_name: master
    ports:
      - "6379:6379"
    networks:
      - redis-replication

  redis-slave:
    image: redis:7.0.4-alpine
    container_name: slave
    ports:
      - "6380:6379"
    command: redis-server --slaveof master 6379
    depends_on:
      - redis
    networks:
      - redis-replication

networks:
  redis-replication:
    driver: bridge